# -*- coding: utf-8 -*-
"""Visualizing Data Distributions and Analysing Relationships.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DFmOYlCUzKa4ub3sBfCBfJPVpFWjwW2J
"""

from google.colab import files
uploaded = files.upload()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import pearsonr

df = pd.read_csv("/content/Health_Monitoring_Dataset.csv")

df.head(10)

df.info()

df.describe()

# Checking Null values
df.isnull().sum()

"""**# Visualizations**"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

df = pd.read_csv("/content/Health_Monitoring_Dataset.csv")
data = df["Blood Pressure (mmHg)"]

q1  = data.quantile(0.25)
med = data.median()
q3  = data.quantile(0.75)
mn  = data.min()
mx  = data.max()

fig, ax = plt.subplots(figsize=(6, 7))
ax.boxplot(data)

# Annotate all 5 values on the plot
for val, label in zip([mn, q1, med, q3, mx],
                      [f"Min = {mn}", f"Q1 = {q1}", f"Median = {med}", f"Q3 = {q3}", f"Max = {mx}"]):
    ax.annotate(label, xy=(1, val), xytext=(1.15, val),
                fontsize=10, va="center",
                arrowprops=dict(arrowstyle="-", color="gray"))

ax.set_title("Box Plot - Blood Pressure (mmHg)")
ax.set_ylabel("Blood Pressure (mmHg)")
ax.set_xticks([1])
ax.set_xticklabels(["All Participants"])
plt.tight_layout()
plt.show()

# Grouped Box Plot with all values labelled
smokers     = df[df["Smoking Status"] == "Yes"]["Blood Pressure (mmHg)"]
non_smokers = df[df["Smoking Status"] == "No"]["Blood Pressure (mmHg)"]

fig, ax = plt.subplots(figsize=(8, 7))
ax.boxplot([non_smokers, smokers], labels=["Non-Smokers", "Smokers"])

for i, group in enumerate([non_smokers, smokers], start=1):
    for val, label in zip(
        [group.min(), group.quantile(0.25), group.median(), group.quantile(0.75), group.max()],
        ["Min", "Q1", "Median", "Q3", "Max"]
    ):
        ax.annotate(f"{label} = {val}", xy=(i, val), xytext=(i + 0.3, val),
                    fontsize=9, va="center",
                    arrowprops=dict(arrowstyle="-", color="gray"))

ax.set_title("Box Plot - Blood Pressure by Smoking Status")
ax.set_ylabel("Blood Pressure (mmHg)")
plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats

df = pd.read_csv("Health_Monitoring_Dataset.csv")

r, p = stats.pearsonr(df["Age"], df["Blood Pressure (mmHg)"])
print(f"Pearson r = {r:.4f}")
print(f"p-value   = {p:.4f}")

# Scatter Plot with Regression Line
import numpy as np

x = df["Age"]
y = df["Blood Pressure (mmHg)"]
m, b = np.polyfit(x, y, 1)

plt.figure(figsize=(7, 5))
plt.scatter(x, y, color="steelblue", edgecolors="black", alpha=0.7)
plt.plot(x, m*x + b, color="red", linewidth=2, label=f"r = {r:.4f}, p = {p:.4f}")
plt.title("Scatter Plot - Age vs Blood Pressure")
plt.xlabel("Age (years)")
plt.ylabel("Blood Pressure (mmHg)")
plt.legend()
plt.tight_layout()
plt.show()

# Correlation Heatmap
import seaborn as sns

corr = df[["Age", "Blood Pressure (mmHg)"]].corr()

plt.figure(figsize=(5, 4))
sns.heatmap(corr, annot=True, fmt=".4f", cmap="coolwarm", linewidths=1)
plt.title("Correlation Heatmap")
plt.tight_layout()
plt.show()